"""genre_matrix

Revision ID: 5a95614f9a40
Revises: ca4ece03dd78
Create Date: 2021-12-30 07:31:56.528915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from seed.datatread import matrix_maker


# revision identifiers, used by Alembic.
revision = '5a95614f9a40'
down_revision = 'ca4ece03dd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre_Matrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('top1', sa.Integer(), nullable=False),
    sa.Column('top2', sa.Integer(), nullable=False),
    sa.Column('top3', sa.Integer(), nullable=False),
    sa.Column('top4', sa.Integer(), nullable=False),
    sa.Column('top5', sa.Integer(), nullable=False),
    sa.Column('top6', sa.Integer(), nullable=False),
    sa.Column('top7', sa.Integer(), nullable=False),
    sa.Column('top8', sa.Integer(), nullable=False),
    sa.Column('top9', sa.Integer(), nullable=False),
    sa.Column('top10', sa.Integer(), nullable=False),
    sa.Column('top11', sa.Integer(), nullable=False),
    sa.Column('top12', sa.Integer(), nullable=False),
    sa.Column('top13', sa.Integer(), nullable=False),
    sa.Column('top14', sa.Integer(), nullable=False),
    sa.Column('top15', sa.Integer(), nullable=False),
    sa.Column('top16', sa.Integer(), nullable=False),
    sa.Column('top17', sa.Integer(), nullable=False),
    sa.Column('top18', sa.Integer(), nullable=False),
    sa.Column('top19', sa.Integer(), nullable=False),
    sa.Column('top20', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    matrix = matrix_maker()
    
    seed_matrix_table = table('Genre_Matrix',
        column('id', sa.Integer),
        column('top1', sa.Integer()),
        column('top2', sa.Integer()),
        column('top3', sa.Integer()),
        column('top4', sa.Integer()),
        column('top5', sa.Integer()),
        column('top6', sa.Integer()),
        column('top7', sa.Integer()),
        column('top8', sa.Integer()),
        column('top9', sa.Integer()),
        column('top10', sa.Integer()),
        column('top11', sa.Integer()),
        column('top12', sa.Integer()),
        column('top13', sa.Integer()),
        column('top14', sa.Integer()),
        column('top15', sa.Integer()),
        column('top16', sa.Integer()),
        column('top17', sa.Integer()),
        column('top18', sa.Integer()),
        column('top19', sa.Integer()),
        column('top20', sa.Integer()),
    )
    op.bulk_insert(seed_matrix_table, matrix)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre_Matrix')
    # ### end Alembic commands ###
