"""2nd migration

Revision ID: 780665ed6473
Revises: b80870cffcd7
Create Date: 2021-12-22 07:25:32.924561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '780665ed6473'
down_revision = 'b80870cffcd7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('open_year', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=80), nullable=False),
    sa.Column('runtime', sa.Time(), nullable=False),
    sa.Column('director', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
    seed_contents = table('Contents',
        column('title', sa.String),
        column('open_year', sa.Integer),
        column('score', sa.Integer),
        column('genre', sa.String),
        column('runtime', sa.Time),
        column('director', sa.String),
        column('image', sa.String),
    )
    op.bulk_insert(seed_contents, [
        {
            'title': '모가디슈',
            'open_year': 2021,
            'score': 79,
            'genre': '액션',
            'runtime': '02:01',
            'director': 'Ryoo Seung-wan',
            'image': 'https://images.justwatch.com/poster/247509899/s276/mogadisyu.webp'
        },
        {
            'title': '지옥',
            'open_year': 2021,
            'score': 83,
            'genre': 'SF',
            'runtime': '00:52',
            'director': 'Yeon Sang-ho',
            'image': 'https://images.justwatch.com/poster/254406538/s276/jiog.webp'
        },
        {
            'title': '그 해 우리는',
            'open_year': 2021,
            'score': 100,
            'genre': '코미디',
            'runtime': '01:07',
            'director': 'Kim Yoon Jin',
            'image': 'https://images.justwatch.com/poster/256797687/s276/geu-hae-urineun.webp'
        },
        {
            'title': '베놈',
            'open_year': 2018,
            'score': 78,
            'genre': '액션',
            'runtime': '01:52',
            'director': 'Ruben Fleischer',
            'image': 'https://images.justwatch.com/poster/245637413/s276/benom.webp'
        },
        {
            'title': '사역소',
            'open_year': 2019,
            'score': 80,
            'genre': '드라마',
            'runtime': '00:32',
            'director': '잘 모름',
            'image': 'https://images.justwatch.com/poster/191247113/s276/sayeogso.webp'
        }
    ])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Contents')
    # ### end Alembic commands ###
