"""initContents

Revision ID: a416710ae2bb
Revises: b80870cffcd7
Create Date: 2021-12-24 04:22:30.812547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from seed.datatread import seed_maker


# revision identifiers, used by Alembic.
revision = 'a416710ae2bb'
down_revision = 'b80870cffcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('origin_title', sa.String(length=255), nullable=True),
    sa.Column('open_year', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rate_count', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Time(), nullable=True),
    sa.Column('director', sa.String(length=80), nullable=True),
    sa.Column('synopsis', sa.TEXT(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('isMovie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('Actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contents_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['contents_id'], ['Contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Buy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contents_id', sa.Integer(), nullable=False),
    sa.Column('ott', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contents_id'], ['Contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contents_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['contents_id'], ['Contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contents_id', sa.Integer(), nullable=False),
    sa.Column('ott', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contents_id'], ['Contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Streaming',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contents_id', sa.Integer(), nullable=False),
    sa.Column('ott', sa.String(length=80), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contents_id'], ['Contents.id'], ),
    sa.PrimaryKeyConstraint('id', 'contents_id')
    )
    # ### end Alembic commands ###
    contents, contents_genre, contents_actor, contents_streaming, contents_buy, contents_rent = seed_maker()

    seed_contents = table('Contents',
        column('id', sa.Integer),
        column('title', sa.String),
        column('origin_title', sa.String),
        column('open_year', sa.Integer),
        column('score', sa.Float),
        column('rate_count', sa.Integer),
        column('runtime', sa.Time),
        column('director', sa.String),
        column('synopsis', sa.TEXT),
        column('image', sa.String),
        column('isMovie', sa.Boolean),
    )
    op.bulk_insert(seed_contents, contents)

    seed_contents_actor = table('Actor',
        column('id', sa.Integer()),
        column('contents_id', sa.Integer),
        column('actor', sa.String),
    )
    op.bulk_insert(seed_contents_actor, contents_actor)

    seed_contents_genre = table('Genre',
        column('id', sa.Integer()),
        column('contents_id', sa.Integer),
        column('genre', sa.String),
    )
    op.bulk_insert(seed_contents_genre, contents_genre)

    seed_contents_streaming = table('Streaming',
        column('id', sa.Integer()),
        column('contents_id', sa.Integer),
        column('ott', sa.String),
        column('price', sa.String),
        column('quality', sa.String),
    )
    op.bulk_insert(seed_contents_streaming, contents_streaming)

    seed_contents_buy = table('Buy',
        column('id', sa.Integer()),
        column('contents_id', sa.Integer),
        column('ott', sa.String),
        column('price', sa.Integer),
        column('quality', sa.String),
    )
    op.bulk_insert(seed_contents_buy, contents_buy)

    seed_contents_rent = table('Rent',
        column('id', sa.Integer()),
        column('contents_id', sa.Integer),
        column('ott', sa.String),
        column('price', sa.Integer),
        column('quality', sa.String),
    )
    op.bulk_insert(seed_contents_rent, contents_rent)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Streaming')
    op.drop_table('Rent')
    op.drop_table('Genre')
    op.drop_table('Buy')
    op.drop_table('Actor')
    op.drop_table('Contents')
    # ### end Alembic commands ###
