"""Initial migration.

Revision ID: b80870cffcd7
Revises: 
Create Date: 2021-12-14 12:22:08.671010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'b80870cffcd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    )
    # ### end Alembic commands ###
    seed_users = table('User',
    column('id', sa.Integer),
    column('name', sa.String),
    column('email', sa.String),
    column('password', sa.String),
)
    op.bulk_insert(seed_users, [{'name':'검정피자', 'email': 'aa@aa.aa', 'password': 'aaa'}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
